### ISSUE TITLE
♻️ refactor: 인적공제, 주택/월세 공제, 중소기업 공제 리팩토링(데이터 변경)

### ISSUE THREAD

**Issue by allllfo** [13th-month-lucky/frontend#75]
## 📌 Description
- 중소기업 공제 수정

**Comment by youhyeoneee** [comment]
## 중소기업 감면
<img width="343" alt="image" src="https://github.com/13th-month-lucky/frontend/assets/37354574/3777e13e-2179-4027-a644-af766735fa6f">

https://www.nts.go.kr/comm/nttFileDownload.do?fileKey=367ee2482174f9ea5814649dd2e9cc37
